let teamList = {
    NBA: ['Atlanta Hawks',
        'Boston Celtics',
        'Brooklyn Nets',
        'Charlotte Hornets',
        'Chicago Bulls',
        'Cleveland Cavaliers',
        'Dallas Mavericks',
        'Denver Nuggets',
        'Detroit Pistons',
        'Golden State Warriors',
        'Houston Rockets',
        'Indiana Pacers',
        'LA Clippers',
        'Los Angeles Lakers',
        'Memphis Grizzlies',
        'Miami Heat',
        'Milwaukee Bucks',
        'Minnesota Timberwolves',
        'New Orleans Pelicans',
        'New York Knicks',
        'Oklahoma City Thunder',
        'Orlando Magic',
        'Philadelphia 76ers',
        'Phoenix Suns',
        'Portland Trail Blazers',
        'Sacramento Kings',
        'San Antonio Spurs',
        'Toronto Raptors',
        'Utah Jazz',
        'Washington Wizards'],
    MLB: ['Atlanta Braves',
        'Miami Marlins',
        'New York Mets',
        'Philadelphia Phillies',
        'Washington Nationals',
        'Chicago Cubs',
        'Cincinnati Reds',
        'Milwaukee Brewers',
        'Pittsburgh Pirates',
        'St. Louis Cardinals',
        'Arizona Diamondbacks',
        'Colorado Rockies',
        'Los Angeles Dodgers',
        'San Diego Padres',
        'San Francisco Giants',
        'Baltimore Orioles',
        'Boston Red Sox',
        'New York Yankees',
        'Tampa Bay Rays',
        'Toronto Blue Jays',
        'Chicago White Sox',
        'Cleveland Indians',
        'Detroit Tigers',
        'Kansas City Royals',
        'Minnesota Twins',
        'Houston Astros',
        'Los Angeles Angels',
        'Oakland Athletics',
        'Seattle Mariners',
        'Texas Rangers'],
    NFL: ['Arizona Cardinals',
        'Atlanta Falcons',
        'Baltimore Ravens',
        'Buffalo Bills',
        'Carolina Panthers',
        'Chicago Bears',
        'Cincinnati Bengals',
        'Cleveland Browns',
        'Dallas Cowboys',
        'Denver Broncos',
        'Detroit Lions',
        'Green Bay Packers',
        'Houston Texans',
        'Indianapolis Colts',
        'Jacksonville Jaguars',
        'Kansas City Chiefs',
        'Miami Dolphins',
        'Minnesota Vikings',
        'New England Patriots',
        'New Orleans Saints',
        'New York Giants',
        'New York Jets',
        'Oakland Raiders',
        'Philadelphia Eagles',
        'Pittsburgh Steelers',
        'Los Angeles Rams',
        'Los Angeles Chargers',
        'San Francisco 49ers',
        'Seattle Seahawks',
        'Tampa Bay Buccaneers',
        'Tennessee Titans',
        'Washington Redskins'],
    NHL: ['Anaheim Ducks',
        'Arizona Coyotes',
        'Boston Bruins',
        'Buffalo Sabres',
        'Calgary Flames',
        'Carolina Hurricanes',
        'Chicago Blackhawks',
        'Colorado Avalanche',
        'Columbus Blue Jackets',
        'Dallas Stars',
        'Detroit Red Wings',
        'Edmonton Oilers',
        'Florida Panthers',
        'Los Angeles Kings',
        'Minnesota Wild',
        'Montreal Canadiens',
        'Nashville Predators',
        'New Jersey Devils',
        'New York Islanders',
        'New York Rangers',
        'Ottawa Senators',
        'Philadelphia Flyers',
        'Pittsburgh Penguins',
        'San Jose Sharks',
        'St Louis Blues',
        'Tampa Bay Lightning',
        'Toronto Maple Leafs',
        'Vancouver Canucks',
        'Vegas Golden Knights',
        'Washington Capitals',
        'Winnipeg Jets']
}

module.exports = teamList;